name: Git action demo
on:
  push: 
    branches:
      - main
      - develop
      - feature/*
      - 'release/*'
      - 'hotfix/*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
jobs:
  job-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v6
      - name: output in index.html
        run: cat index.html
  
    
