name: hello world
on:
  push: 
    branches:
      - main
      - develop
      - feature/*
      - 'release/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy job
        run: echo "job deployed"
  
    
