name: if with conditions demo
on:
    push:
        branches: 
            - devlop
            - main
            - feature/*
    # pull_request:
    #     branches: 
    #         - feature/*
jobs:
  quality-check:
    if: (github.event_name == 'push' && startsWith(github.ref_name, 'feature/')) 
    # if: (github.event_name == 'push' && startsWith(github.ref_name, 'feature/')) || 
    #     (github.event_name == 'pull_request' && startsWith(github.head_ref, 'feature/'))
    runs-on: ubuntu-latest
    steps:
      - name: perform quality check
        run: |
          echo "Performing quality check for feature branch push or PR event"
          exit 1 # Simulating a failure in quality check for demonstration purposes
  
  devlop-deploy:
    if: github.ref_name == 'devlop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: deploy to devlop environment  
        run: echo "Deploying to devlop environment for devlop branch push event"
  production-deploy:
    if: github.ref_name == 'main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: deploy to production environment
        run: echo "Deploying to production environment for main branch push event"

  success-email:
    needs: [quality-check, devlop-deploy, production-deploy]
    if: always() && !failure()
    runs-on: ubuntu-latest
    steps:
      - name: send success email
        run: echo "Sending success email for feature branch event"

  failure-email:
    needs: [quality-check, devlop-deploy, production-deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: send failure email
        run: echo "Sending failure email for feature branch event"
