name: static website publish on s3
on: push
permissions:
  id-token: write
  contents: read
jobs:
  deploy_the_website:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v6
        
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-south-1
          
      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE}}
          aws-region: ap-south-1
          
      - name: deploy code on s3
        run: |
          aws s3 sync ./ s3://git-s3-chicku-demo-bucket/ \
          -- exclude "*" \
          -- include "index.html"
          
        
  
